shell.run("wget", "-O https://github.com/Portablefire22/ComputerCraftATM9/blob/main/storage_controller/update.lua")
shell.run("wget", "-O https://github.com/Portablefire22/ComputerCraftATM9/blob/main/storage_controller/grid_api.lua", "grid_api.lua")
shell.run("wget", "-O https://github.com/Portablefire22/ComputerCraftATM9/blob/main/storage_controller/startup.lua", "startup.lua")
shell.run("wget", "-O https://github.com/Portablefire22/ComputerCraftATM9/blob/main/storage_controller/gui.lua", "gui.lua")
shell.run("wget", "-O https://github.com/Portablefire22/ComputerCraftATM9/blob/main/storage_controller/item_translator.lua", "item_translator.lua")
